/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 25 20:59:56 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[2];
      StackTraceElement[] stackTraceElementArray1 = new StackTraceElement[3];
      boolean boolean0 = target0.__target__(stackTraceElementArray0, stackTraceElementArray1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[2];
      StackTraceElement stackTraceElement0 = new StackTraceElement("", "", "", 1);
      stackTraceElementArray0[0] = stackTraceElement0;
      StackTraceElement[] stackTraceElementArray1 = new StackTraceElement[2];
      boolean boolean0 = target0.__target__(stackTraceElementArray0, stackTraceElementArray1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[2];
      StackTraceElement stackTraceElement0 = new StackTraceElement("", "", "", 1);
      stackTraceElementArray0[0] = stackTraceElement0;
      // Undeclared exception!
      try { 
        target0.__target__(stackTraceElementArray0, stackTraceElementArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[2];
      StackTraceElement[] stackTraceElementArray1 = new StackTraceElement[3];
      boolean boolean0 = target0.__target__(stackTraceElementArray1, stackTraceElementArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[0];
      Target target0 = new Target();
      boolean boolean0 = target0.__target__(stackTraceElementArray0, stackTraceElementArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      boolean boolean0 = target0.__target__((StackTraceElement[]) null, (StackTraceElement[]) null);
      assertFalse(boolean0);
  }
}
