/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 21:07:21 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[6];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, (byte) (-93), 572, byteArray0, (byte)0, 2160);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[11];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, (-1), 250, byteArray0, 3, 2776);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, (byte)0, (-1), byteArray0, (byte)1, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      int int0 = target0.__target__((byte[]) null, (-122), (-122), (byte[]) null, (-122), (-122));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[4];
      int int0 = target0.__target__(byteArray0, (byte)1, (byte)1, byteArray0, (byte)1, 1364);
      assertArrayEquals(new byte[] {(byte)0, (byte) (-25), (byte) (-62), (byte)62}, byteArray0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[4];
      int int0 = target0.__target__(byteArray0, (byte) (-25), 1329, byteArray0, 4318, (-1831));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((byte[]) null, 253, 250, (byte[]) null, 3556, 253);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[2];
      int int0 = target0.__target__(byteArray0, 2474, (byte)0, byteArray0, (byte)0, (byte)0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[4];
      int int0 = target0.__target__(byteArray0, (byte)1, (byte)1, byteArray0, (byte)0, 318);
      assertArrayEquals(new byte[] {(byte) (-25), (byte)45, (byte) (-62), (byte)0}, byteArray0);
      assertEquals(3, int0);
  }
}
